
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.6.71-3.0.11.kos5.x86_64 - x86_64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/zjj/.conda/envs/vllm-cpu/lib/python3.12/site-packages/cmake/data/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.6.71-3.0.11.kos5.x86_64 - x86_64
...
